/*
 * Auto-generated by Frida. Please modify to match the signature of _Thrd_sleep.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 */

defineHandler({
  onEnter(log, args, state) {
    log('_Thrd_sleep()');
    args[0] = 1;
  },

  onLeave(log, retval, state) {
  }
});
